name: Export Secrets
on: pull_request  # Runs on PR creation, then close PR without merging

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      # For better security: fork, audit, and use your own copy (see ADVANCED.md)
      - uses: gerrywastaken/github-secrets-exporter@main
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}
        with:
          public_encryption_key: 'age16w8quuvlmcqexj7elh0hgf4q4e5qt7xee4eju0rwwt7ell0rtg9q25wpvz'
